### PR TITLE
Ym manage profile

### PR DESCRIPTION
**Pull request by marcinky**
Still need to figure out how to put a checkbox in there, but there is a Manage Profiles page now. It doesn't do anything though.
I did run into some issues when doing git rebase original master but, it turns out that I added the manage profiles page to App.js and Jen also made changes to App.js. I resolved the conflicts and made sure that it still compiled before making this PR.

### CODE REVIEW

**Review by witherst — APPROVED** [review]
1000%

**Comment by jeh018** [comment]
im noticing conflicts with your branch. its not in line with master

**Review by jeh018 — CHANGES_REQUESTED** [review]
pls rebase

in your branch...

git pull --rebase origin master

when you're done fixing the merge conflicts, you can then 
git push
you might have to add in the -f flag (git push -f)

**Comment by marcinky** [comment]
I can't figure out how to fix the conflicts. Closing this PR and doing a new branch.

**Pull request closed without merging**
